---
# Optionally Add Repos
- name: Add Repos
  when: _rs_collector.apt_repos is defined
  block:
    - name: Add Repo Signing Keys
      ansible.builtin.apt_key:
        id: "{{ item.key_id }}"
        url: "{{ item.key_url }}"
      with_items: "{{ _rs_collector.apt_repos }}"

    - name: Add Apt Repo
      ansible.builtin.apt_repository:
        repo: "{{ item.repo_line }}"
        state: present
      with_items: "{{ _rs_collector.apt_repos }}"
      register: repo_added

    - name: Apt Update
      ansible.builtin.apt:
        update_cache: yes
      when: RW_APT_CACHE_UPDATE is defined or repo_added is changed

- name: Set install_state
  ansible.builtin.set_fact:
    install_state: latest
  when: RW_ENABLE_DOWNLOADS is defined

- name: Install rs-collector # noqa args[module]
  ansible.builtin.apt:
    name: rs-collector
    state: "{{ install_state | default('present') }}"

- name: Add SSL_CERT_DIR as env variable in rs-collector startup (upstart)
  ansible.builtin.lineinfile:
    line: "env SSL_CERT_DIR=/etc/ssl/certs"
    state: present
    insertbefore: "pre-start script"
    dest: "/etc/init/rs-collector.conf"
  when: ansible_service_mgr == "upstart"

- name: Add SSL_CERT_DIR as env variable in rs-collector startup (systemd)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - "etc/systemd/system/rs-collector.service.d/50-env-ssl-dir.conf"
  when: ansible_service_mgr == "systemd"

- name: Log to dedicated log file (systemd)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - "etc/systemd/system/rs-collector.service.d/20-stdout-err.conf"
  when: ansible_service_mgr == "systemd"

- name: Enable rs-collector
  ansible.builtin.service:
    name: rs-collector
    enabled: yes

- name: Configure rs-collector
  ansible.builtin.template:
    src: etc/rs-collector.conf.j2
    dest: /etc/rs-collector.conf
    owner: root
    group: root
    mode: 0640
  when: _rs_collector.use_default_config
  notify:
    - Restart rs-collector
